Enclose b2c inside tryton-model
coopengo/tryton-model pull request #11
Opened 2018-08-21 14:59 UTC by PierreCookie

Fix #9576

2018-08-21 15:47 UTC, jmousset requested changes

2018-08-21 15:47 UTC, jmousset commented on lib/index.js
> +    args[0] = alterDomain(this.session.party, this.model.name, args[0])
ça devrait juste prendre en argument this.session, et si y a des restrictions de domaines défini dans la session, les appliquer.

2018-08-22 14:37 UTC, FlorianDesjouis approved these changes

2018-08-22 14:37 UTC, FlorianDesjouis commented on lib/session.js
> +    debug('init party token')
C'est normal ça ? ou c'est un oublie de debug

2018-08-22 15:04 UTC, PierreCookie commented on lib/session.js
> +    debug('init party token')
C'est normal :)

2018-08-22 15:29 UTC, jmousset commented on lib/index.js
> +        assert(result || !this.session.party, 'you can`t access this record')
cannot plutôt (et un backtilde c'est un peu bizarre non ?)

2018-08-22 15:29 UTC, jmousset commented on lib/index.js
> +  assert(this.session.party('you can\'t delete a record'))
c'est le contraire plutôt non ?

2018-08-22 15:57 UTC, PierreCookie commented on lib/index.js
> +        assert(result || !this.session.party, 'you can`t access this record')
can't = cannot
@done

2018-08-22 15:58 UTC, PierreCookie commented on lib/index.js
> +  assert(this.session.party('you can\'t delete a record'))
@done

2018-08-22 16:20 UTC, jmousset approved these changes
demande à jean si can't == cannot :D

2018-08-29 15:47 UTC, merged