Remove group record is reading checker
coopengo/tryton-model pull request #16
Opened 2019-11-13 15:50 UTC by PierreCookie

2019-12-02 10:54 UTC, jmousset commented on lib/index.js
> -  assert(this.every((rec) => !rec.isReading()), 'concurrent request')
pourquoi ?

2019-12-02 12:45 UTC, JCavallo requested changes
Il me faudrait une explication d'exactement dans quel cas il y avait besoin de faire ça...

2019-12-02 14:20 UTC, PierreCookie commented
La souscritption multi assuré en V1 ne marche plus suite a un fix de la supression du cache des données complémentaires...

2019-12-03 09:07 UTC, JCavallo commented
@PierreCookie Ma question, c'est la ligne originale, à quoi elle servait.

2019-12-05 13:41 UTC, PierreCookie commented
@JCavallo je pense que cette ligne sert a ne pas écrire sur la variable partagée dans le cache de session en même temps.
Mais c'est un hotfix qu'on peut régler dans algorithmie de coog-api, donc si je prend le temps de changer le code de coog-api on peut reject cette pr, Sauf que c'est le code de contract/covered :/

2019-12-05 15:32 UTC, JCavallo commented
C'est le genre de hotfix pour un cas particulier ou on prend le risque de casser le cas général, donc je suis vraiment pas chaud...

2019-12-11 09:28 UTC, closed without merging

2019-12-11 09:29 UTC, PierreCookie commented
Delete car gérais par: https://github.com/coopengo/coog-api/pull/331