session: add generic method to check if a module is installed
coopengo/tryton-model pull request #7
Opened 2018-06-01 15:45 UTC by ClemFaure

Ref #8974

2018-06-04 12:54 UTC, jmousset approved these changes

2018-06-04 12:54 UTC, jmousset commented on lib/session.js
> +
une ligne vide en trop là non ? tu peux utiliser npm format (la commande) normalement pour formater automatiquement le code.

2018-06-04 13:00 UTC, jmousset requested changes
il manque un bout où on déclare la méthode rpc coog qui liste les modules

2018-06-07 16:22 UTC, manalaboutayeb approved these changes

2018-06-08 07:44 UTC, PierreCookie approved these changes

2018-06-08 07:53 UTC, AdrienBenduc commented on lib/session.js
> +    debug('init module')
debug ? was dat ?

2018-06-08 08:21 UTC, PierreCookie commented on lib/session.js
> +    debug('init module')
Si tu lance l'application en mode débug, ça t'affiche des logs supplémentaires.

2018-06-08 13:45 UTC, jmousset approved these changes

2018-06-08 13:47 UTC, merged